export const ADD_COUNTER = "counter/ADD_COUNTER";
export const REDUCER_COUNTER = "counter/REDUCER_COUNTER";

export const GET_USER_REQUEST = "other/GET_USER_REQUEST";
export const GET_USER_SUCCESS = "other/GET_USER_SUCCESS";
export const GET_USER_FAILURE = "other/GET_USER_FAILURE";

export const GET_PRODUCT_REQUEST = "product/GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "product/GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "product/GET_PRODUCT_FAILURE";

export const GET_PRODUCT_BY_ID_REQUEST = "product/GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "product/GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILURE = "product/GET_PRODUCT_BY_ID_FAILURE";

export const GET_PRODUCT_WISHLIST_REQUEST =
  "product/GET_PRODUCT_WISHLIST_REQUEST";
export const GET_PRODUCT_WISHLIST_SUCCESS =
  "product/GET_PRODUCT_WISHLIST_SUCCESS";
export const GET_PRODUCT_WISHLIST_FAILURE =
  "product/GET_PRODUCT_WISHLIST_FAILURE";

export const SEARCH_PRODUCT_REQUEST = "product/SEARCH_PRODUCT_REQUEST";
export const SEARCH_PRODUCT_SUCCESS = "product/SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_FAILURE = "product/SEARCH_PRODUCT_FAILURE";
